### ISSUE TITLE
[Suggestion] Rain angle option

### ISSUE THREAD

**Issue by Tostereek** [PigCart/particle-rain#40]
Maybe add option to set rain angle value and thunderstorm multiplier for it

**Comment by scramble-cat** [comment]
I second this! The angle at the moment makes it so that standing in a biome such as frozen peaks will render rain instead of snow, and the snow is severely displaced off to the side. Turning on the 'render vanilla weather' setting helps with this, but that sort of defeats the point of having the mod installed. Would love for this to be an option!

**Comment by Godrend** [comment]
it would be epic if the rain angle could change dynamically throughout time, adding another level of realism and immersion into rain and thunderstorms
