### ISSUE TITLE
new version breaks partical and texture

### ISSUE THREAD

**Issue by shinycolororange** [PigCart/particle-rain#64]
![2024-12-18_04 22 19](https://github.com/user-attachments/assets/10c653a5-4b98-42e6-b237-9487bbaeb73d)
the new update looks cool sadly it does break water partical and does not even show me rain in anybiome.

fabric 1.21.1, partical fog version 3.0 going back  a version everything works again

**Comment by shinycolororange** [comment]
while testing to make sure its not one of my mods/texturepack i installed the new version on a fresh install 1.21.1 fabric with only sodium/lithium and it crashed when raining, https://mclo.gs/pnf2LTK

**Comment by BlueHDGaming** [comment]
I have the same issue. With my modpack installed (around 130 Mods) I can see the rain particles, however they render as missing textures. The games also crashes when it starts raining if you don't have lithium installed, just sodium (same crash-report). If you don't have sodium installed the game is just stuck in the loading screen.
Hope this gets fixed soon, because it is really a great mod!

**Comment by zed1ker** [comment]
![image](https://github.com/user-attachments/assets/5738a6dc-9339-439e-81b2-7ef4748fbf9a)

**Comment by shinycolororange** [comment]
looks like the new updates fixes alot of issues one i still found glass partical and rain in savana / sand storm in flat redstone ready preset not working

**Comment by PigCart** [comment]
That is unrelated. Disable Y-level wind adjustment if you want wind in superflat worlds.

**Comment by shinycolororange** [comment]
a thanks for the info!
