### ISSUE TITLE
can i port and maintain this to NeoForge ?

### ISSUE THREAD

**Issue by Leclowndu93150** [PigCart/particle-rain#70]
hi, basicaly the title says it all
https://www.curseforge.com/members/project8gbderam/projects
this is my curseforge page, i make lots of mods and ports. and someone asked me to port yours so i would really love to !

**Comment by PigCart** [comment]
sure

**Comment by Leclowndu93150** [comment]
1 hour is a record for sure. btw nice mod, it is very configurable, i love it
![1KIVRPz1Cb](https://github.com/user-attachments/assets/c2533c3f-2575-49ee-8661-daa2f53a8185)

**Comment by V972** [comment]
Greetings.
I really like ths mod. I really want it in my modpack.
So, where and how much do I need to drop in generous donations for it to also get ported and kinda semi-maintained (meaning critical bugfixes and maybe occasional feature ports) to...1.18.2 Forge. 
Yes, I know. This is why I offer donations (to both of you BTW, not just Leclowndu93150), I don't expect it to be ported otherwise (understandably, frankly).
I'm serious about this.

**Comment by Leclowndu93150** [comment]
You can commision me for a backport

**Comment by V972** [comment]
> You can commission me for a backport
Sorry for late reply
@Leclowndu93150 Awesome!
I will contact you on Discord (the one stated on your GitHub page) shortly then! You're recognize my Profile picture.

And @PigCart I couldn't find any dono link so feel free to drop it, because w/o you there wouldn't be the mod in the first place!

**Comment by Leclowndu93150** [comment]
> > You can commission me for a backport  
> 
> Sorry for late reply
> @Leclowndu93150 Awesome!
> I will contact you on Discord (the one stated on your GitHub page) shortly then! You're recognize my Profile picture.
> 
> And @PigCart I couldn't find any dono link so feel free to drop it, because w/o you there wouldn't be the mod in the first place!

Hey have you managed to add me ?
